from pathlib import Path
p=Path('scripts/nayanethub-final-execution.js')
s=p.read_text(encoding='utf-8')
s=s.replace("const NAME='nayanet_smart_name',NOTES='nayanet_v7_live_notes',LISTS='nayanet_v7_smart_lists',COLLECTIVE='nayanet_v7_collective_blocks',ENGAGE='nayanet_v7_collective_engagement';", "const NAME='nayanet_smart_name',NOTES='nayanet_v7_live_notes',LISTS='nayanet_v7_smart_lists',COLLECTIVE='nayanet_v7_collective_blocks',ENGAGE='nayanet_v7_collective_engagement',FAVS='nayanet_v7_favorites';")
s=s.replace("function collective(){return load(COLLECTIVE,[])}", "function collective(){const refs=load(COLLECTIVE,[]);const ids=refs.map(x=>typeof x==='string'?x:x&&x.id).filter(Boolean);return [...new Set(ids)].map(id=>resolveNote(id)).filter(Boolean)}\nfunction resolveNote(id){const n=load(NOTES,[]).find(x=>x.id===id);if(!n)return null;return {id:n.id,title:(String(n.text||'').split(/[.!?]\\s+/)[0]||'Intelligent Event').replace(/^#+\\s*/,'').slice(0,100),summary:String(n.text||''),type:n.type||'INSIGHT',createdAt:n.createdAt||new Date().toISOString()}}")
s=s.replace("function smartLists(){return load(LISTS,[])}", "function favorites(){return load(FAVS,[])}\nfunction smartLists(){return load(LISTS,[]).map(l=>({id:l.id,name:l.name,items:(l.items||[]).map(x=>typeof x==='string'?x:x.id).filter(Boolean)}))}\nfunction persistLists(v){save(LISTS,v)}\nfunction resolveBlock(id){return notes().find(x=>x.id===id)||collective().find(x=>x.id===id)||null}\nfunction migrateCollective(){const refs=load(COLLECTIVE,[]);const ids=[...new Set(refs.map(x=>typeof x==='string'?x:x&&x.id).filter(Boolean))];save(COLLECTIVE,ids);return ids}")
s=s.replace("function welcome(){css();const n=esc(name()),d=new Date(),g=d.getHours()<12?'Good morning':d.getHours()<17?'Good afternoon':'Good evening',t=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),dt=d.toLocaleDateString([],{weekday:'long',year:'numeric',month:'long',day:'numeric'}),c=esc(country());let el=document.getElementById('nayanethub-personal-welcome');if(!el){el=document.createElement('section');el.id='nayanethub-personal-welcome';(document.querySelector('#page-home')||document.querySelector('main')||document.body).prepend(el)}el.innerHTML='<div><div class=\"greeting\">'+g+(n?', '+n:'')+'.</div><div class=\"details\">'+t+' · '+dt+(c?' · '+c:'')+'</div></div>'}", "function welcome(){css();const n=esc(name()),d=new Date(),g=d.getHours()<12?'Good morning':d.getHours()<17?'Good afternoon':'Good evening',t=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),dt=d.toLocaleDateString([],{weekday:'long',year:'numeric',month:'long',day:'numeric'}),c=esc(country());const old=document.getElementById('nayaAuthoritativeGreeting');if(old)old.style.display='none';let el=document.getElementById('nayanethub-personal-welcome');if(!el){el=document.createElement('section');el.id='nayanethub-personal-welcome';(document.querySelector('#page-home')||document.querySelector('main')||document.body).prepend(el)}el.innerHTML='<div><div class=\"greeting\">'+g+(n?', '+n:'')+'.</div><div class=\"details\">'+t+' · '+dt+(c?' · '+c:'')+'</div></div><button class=\"btn small purple\" id=\"nh-v4-edit-identity\">'+(n?'EDIT IDENTITY':'ENTER NAME / ALIAS')+'</button>';el.querySelector('#nh-v4-edit-identity').onclick=createIdentity}")
s=s.replace("function card(b,kind){const e=eng(b.id),social=kind==='collective';let a='<div class=\"nh-v4-actions\"><button class=\"primary\" data-save=\"'+esc(b.id)+'\" data-kind=\"'+kind+'\">🔖 SAVE</button>';if(social)a+='<button data-like=\"'+esc(b.id)+'\">'+(e.liked?'♥ LIKED':'♡ LIKE')+' '+e.likes+'</button><button data-comment=\"'+esc(b.id)+'\">💬 COMMENT '+((e.comments||[]).length||'')+'</button>';a+='<button data-share=\"'+esc(b.id)+'\" data-kind=\"'+kind+'\">＋ SHARE</button>';return '<article class=\"nh-v4-card '+(social?'collective':'')+'"><div class=\"nh-v4-head\"><span>'+esc(b.createdAt?new Date(b.createdAt).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'PRESERVED')+'</span><span class=\"nh-v4-source\">'+kind.toUpperCase()+'</span></div><div class=\"nh-v4-body\"><h3>'+esc(b.title||'Intelligent Event')+'</h3><p>'+esc(b.summary||'')+'</p></div>'+a+'</article>'}", "function card(b,kind){const e=eng(b.id),social=kind==='collective',fav=favorites().includes(b.id);let a='<div class=\"nh-v4-actions\"><button class=\"nh-v4-fav '+(fav?'on':'')+'\" data-fav=\"'+esc(b.id)+'\">'+(fav?'★ FAVORITED':'☆ FAVORITE')+'</button><button class=\"primary\" data-save=\"'+esc(b.id)+'\" data-kind=\"'+kind+'\">🔖 SAVE TO SMART LIST</button>';if(social)a+='<button data-like=\"'+esc(b.id)+'\">'+(e.liked?'♥ LIKED':'♡ LIKE')+' '+e.likes+'</button><button data-love=\"'+esc(b.id)+'\">'+(e.loved?'♥ LOVED':'♡ LOVE')+'</button><button data-comment=\"'+esc(b.id)+'\">💬 COMMENT '+((e.comments||[]).length||'')+'</button><span class=\"nh-v4-rating\">'+[1,2,3,4,5].map(i=>'<button data-rate=\"'+esc(b.id)+'\" data-rating=\"'+i+'\">'+(e.rating>=i?'★':'☆')+'</button>').join('')+'</span>';a+='<button data-share=\"'+esc(b.id)+'\" data-kind=\"'+kind+'\">＋ SHARE</button>';return '<article class=\"nh-v4-card '+(social?'collective':'')+'"><div class=\"nh-v4-head\"><span>'+esc(b.createdAt?new Date(b.createdAt).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'PRESERVED')+'</span><span class=\"nh-v4-source\">'+kind.toUpperCase()+'</span></div><div class=\"nh-v4-body\"><h3>'+esc(b.title||'Intelligent Event')+'</h3><p>'+esc(b.summary||'')+'</p></div>'+a+'</article>'}")
start=s.index('function saveToLists('); end=s.index('\nfunction share(',start)
s=s[:start]+'''function saveToLists(id,kind){const src=resolveBlock(id);if(!src)return;const ls=smartLists(),m=document.createElement('div');m.className='nh-v4-modal open';m.innerHTML='<div class="nh-v4-dialog"><h2>SAVE TO SMART LISTS</h2><p>Saving organizes the existing intelligent block. It never publishes it.</p><div class="nh-v4-checks">'+(ls.length?ls.map(l=>'<label class="nh-v4-check"><input type="checkbox" value="'+esc(l.id)+'" '+(l.items.includes(src.id)?'checked':'')+'>'+esc(l.name)+'</label>').join(''):'<div class="nh-v4-empty"><strong>No Smart Lists yet.</strong><span>Create one below.</span></div>')+'</div><input id="nh-v4-newlist" placeholder="Create a new Smart List…"><div class="nh-v4-modal-actions"><button data-close>CANCEL</button><button class="primary" id="nh-v4-save">SAVE</button></div></div>';document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#nh-v4-save').onclick=()=>{let a=smartLists(),newName=m.querySelector('#nh-v4-newlist').value.trim(),ids=[...m.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);if(newName){const n={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:newName,items:[]};a.push(n);ids.push(n.id)}a=a.map(l=>Object.assign({},l,{items:ids.includes(l.id)?[...new Set([...l.items,src.id])]:l.items.filter(x=>x!==src.id)}));persistLists(a);m.remove();renderLists()}}''' + s[end:]
start=s.index('function renderLists('); end=s.index('\nfunction setup(',start)
s=s[:start]+'''function renderLists(){const r=document.getElementById('page-smart-lists-body');if(!r)return;const a=smartLists();r.innerHTML='<div class="nh-v4-listbar"><button class="primary" id="nh-v4-create-list">＋ CREATE SMART LIST</button><input class="search" id="nh-v4-list-search" placeholder="Search Smart Lists…"></div>'+(a.length?a.map(l=>'<section class="nh-v4-list" data-list-name="'+esc(l.name.toLowerCase())+'"><div class="nh-v4-listhead"><h3>'+esc(l.name)+'</h3><span>'+l.items.length+' BLOCKS</span></div><div class="nh-v4-listitems">'+(l.items.length?l.items.map(id=>{const x=resolveBlock(id);return x?'<div class="nh-v4-listitem"><b>'+esc(x.title)+'</b><span>'+esc(x.id)+' · '+esc(x.type||'INSIGHT')+'</span><button data-remove-list="'+esc(l.id)+'" data-remove-id="'+esc(x.id)+'">REMOVE</button></div>':''}).join(''):'<div class="nh-v4-empty"><strong>Empty Smart List</strong><span>Save Personal or Collective intelligence here.</span></div>')+'</div></section>').join(''):'<div class="nh-v4-empty"><strong>Your Smart Lists start here.</strong><span>Create multiple private groupings and organize the same real intelligent block in more than one list.</span></div>';r.querySelector('#nh-v4-list-search').oninput=e=>{const q=e.target.value.toLowerCase();r.querySelectorAll('[data-list-name]').forEach(x=>x.style.display=x.dataset.listName.includes(q)?'':'none')};r.querySelector('#nh-v4-create-list').onclick=()=>{const m=document.createElement('div');m.className='nh-v4-modal open';m.innerHTML='<div class="nh-v4-dialog"><h2>CREATE SMART LIST</h2><input id="nh-v4-listname" placeholder="AI Ideas, Business, Things to Learn…"><div class="nh-v4-modal-actions"><button data-close>CANCEL</button><button class="primary" id="nh-v4-make">CREATE</button></div></div>';document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#nh-v4-make').onclick=()=>{const n=m.querySelector('#nh-v4-listname').value.trim();if(!n)return;const x=smartLists();x.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:n,items:[]});persistLists(x);m.remove();renderLists()}};r.querySelectorAll('[data-remove-list]').forEach(b=>b.onclick=()=>{const x=smartLists(),l=x.find(z=>z.id===b.dataset.removeList);if(!l)return;l.items=l.items.filter(id=>id!==b.dataset.removeId);persistLists(x);renderLists()})}''' + s[end:]
if 'function createIdentity(' not in s:
    pos=s.index('function renderLists(')
    s=s[:pos]+'''function createIdentity(){const current=name(),m=document.createElement('div');m.className='nh-v4-modal open';m.innerHTML='<div class="nh-v4-dialog"><h2>WELCOME TO YOUR HUB</h2><p>Enter your name or alias. This is the only user identity used by the Hub.</p><input id="nh-v4-name" value="'+esc(current)+'" placeholder="Your name or alias"><div class="nh-v4-modal-actions"><button data-close>CANCEL</button><button class="primary" id="nh-v4-name-save">SAVE IDENTITY</button></div></div>';document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('#nh-v4-name-save').onclick=()=>{const v=m.querySelector('#nh-v4-name').value.trim();if(!v)return;save(NAME,v);m.remove();welcome()}}\n''' + s[pos:]
s=s.replace("function setup(){css();welcome();addNav();", "function setup(){css();smartLists();migrateCollective();welcome();addNav();")
s=s.replace("const a=collective();if(!a.some(x=>x.id===src.id)){a.push(Object.assign({},src,{source:'COLLECTIVE',visibility:'collective',collective:true,circulatedAt:new Date().toISOString()}));save(COLLECTIVE,a)}", "const ids=load(COLLECTIVE,[]).map(x=>typeof x==='string'?x:x&&x.id).filter(Boolean);if(!ids.includes(src.id)){ids.push(src.id);save(COLLECTIVE,[...new Set(ids)])}")
s=s.replace("if(sv){saveToLists(sv.dataset.save,sv.dataset.kind);return}", "const fv=e.target.closest('[data-fav]');if(fv){let a=favorites();a=a.includes(fv.dataset.fav)?a.filter(x=>x!==fv.dataset.fav):[...a,fv.dataset.fav];save(FAVS,a);renderPersonal();renderCollective();return}if(sv){saveToLists(sv.dataset.save,sv.dataset.kind);return}")
s=s.replace("if(lk){like(lk.dataset.like);return}", "if(lk){like(lk.dataset.like);return}const lv=e.target.closest('[data-love]');if(lv){const x=eng(lv.dataset.love);x.loved=!x.loved;setEng(lv.dataset.love,x);renderCollective();return}const rt=e.target.closest('[data-rate]');if(rt){const x=eng(rt.dataset.rate);x.rating=Number(rt.dataset.rating);setEng(rt.dataset.rate,x);renderCollective();return}")
for token in ['FAVS','resolveBlock','migrateCollective','data-love','data-rate','Search Smart Lists','nh-v4-edit-identity']:
    if token not in s: raise SystemExit('missing validation token: '+token)
Path('scripts/nayanethub-final-execution.js').write_text(s,encoding='utf-8')
html=Path('NAYANETHUB.html').read_text(encoding='utf-8')
marker='<!-- NAYANETHUB-FINAL-EXECUTION-V1 -->'
if marker not in html: raise SystemExit('final execution marker missing')
start=html.index(marker)
script_start=html.index('<script id="nayanethub-final-execution">',start)
body_start=html.index('>',script_start)+1
end=html.index('</script>',body_start)
new_html=html[:body_start]+s+html[end:]
new_html=new_html.replace('<h1 id="nayaAuthoritativeGreeting">Welcome.</h1>','<h1 id="nayaAuthoritativeGreeting" style="display:none">Welcome.</h1>',1)
Path('NAYANETHUB.html').write_text(new_html,encoding='utf-8')
assert new_html.count('<!doctype html>')==1 and new_html.count('</html>')==1
assert 'FAVS' in new_html and 'data-love' in new_html and 'data-rate' in new_html and 'resolveBlock' in new_html
assert 'prompt(' not in new_html
print('PATCH_OK',len(new_html.encode('utf-8')))
Path('scripts/nayanethub-surgical-patch-v5.py').unlink()
Path('.github/workflows/nayanethub-surgical-patch-v5.yml').unlink()
