"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

const WORLDS=[
{id:"power",name:"Naya Power",icon:"☀",glow:"#9b7cff",kicker:"THE INTELLIGENCE LAYER",title:"Think with more power.",copy:"Naya Power is the intelligence layer for thinking, learning, creating, remembering, organizing, communicating, discovering and accomplishing.",items:[["THINK","Turn questions into clearer thinking and better decisions."],["CREATE","Move from idea to useful work with an intelligent partner."],["GROW","Use every interaction to become more capable."]]},
{id:"brain",name:"Super Brain",icon:"✦",glow:"#8e7bff",kicker:"YOUR PRIVATE INTELLIGENCE",title:"Build intelligence that stays with you.",copy:"Your Super Brain keeps meaningful context, experience and learning available so tomorrow can begin with what you learned today.",items:[["EXPERIENCE","What happens to you can become signal."],["MEMORY","Important context does not have to disappear with a chat."],["COMPOUND","Experience becomes reusable intelligence."]]},
{id:"identity",name:"Smart Identity",icon:"◈",glow:"#ffd56a",kicker:"YOUR IDENTITY",title:"Be known by what you choose.",copy:"NayaNET separates private identity from network identity. Your Smart ID lets you participate deliberately without exposing everything about you.",items:[["SMART NAME","Start with the name you choose."],["SMART ID","Your network identity is distinct from private details."],["SMART LINK","Connect around a deliberate identity."]]},
{id:"notes",name:"Smart Notes",icon:"◇",glow:"#75f0ad",kicker:"CAPTURE WHAT MATTERS",title:"Turn experience into intelligence.",copy:"A breakthrough, lesson, mistake, decision, goal or discovery should not vanish into yesterday. Capture the useful part and make tomorrow smarter.",items:[["HUMAN NOTE","What you experienced."],["NAYA NOTE","What Naya understood."],["COMPOUND","What the system should carry forward."]]},
{id:"maxess",name:"MAXESS",icon:"◉",glow:"#9b7cff",kicker:"AI MASTERY",title:"Find your starting point.",copy:"MAXESS turns AI capability into something you can see, understand and improve. Discover your score and your next move.",items:[["ASSESS","A focused AI mastery assessment."],["UNDERSTAND","See capability clearly."],["ACT","Turn insight into a better way of working." ]],action:"score"},
{id:"challenge",name:"5-Day Challenge",icon:"5",glow:"#ffd56a",kicker:"FIVE DAYS",title:"Don't believe it. Try it.",copy:"Work with Naya on something real. Capture what matters. Learn each day. Five days is enough to feel the difference between using AI and building intelligence with AI.",items:[["DAY 1","Meet the system and establish context."],["DAYS 2–4","Create, learn, capture and compound."],["DAY 5","Look back and see what changed."]],action:"challenge"},
{id:"spaces",name:"Intelligent Spaces",icon:"◎",glow:"#55e6ff",kicker:"COLLABORATION",title:"Open a room around the work.",copy:"An Intelligent Space can bring a human, Naya, other AIs, or other people together around one purpose — privately by default, with sharing by choice.",items:[["PEOPLE","Invite the people who belong."],["AI","Bring Naya or multiple AIs into the work."],["PURPOSE","The space exists to help something happen."]]},
{id:"network",name:"Your Network",icon:"⊙",glow:"#55e6ff",kicker:"INTELLIGENCE CAN FIND INTELLIGENCE",title:"Connect around what matters.",copy:"The future network is not about exposing everyone to everyone. It helps useful intelligence find useful intelligence, with consent at the boundary.",items:[["DISCOVER","Subjects, interests, questions, goals and capabilities."],["CONNECT","Meet people around ideas rather than identity alone."],["SHARE","Choose what wisdom can travel beyond your private space."]]},
{id:"player",name:"Power Player",icon:"▶",glow:"#ffd56a",kicker:"NAYA POWERCAST",title:"Listen. Think. Become more capable.",copy:"The Power Player is the heartbeat of NayaNET — real Powercasts, real ideas and a living listening experience that stays close while you explore.",items:[["LISTEN","Select a canonical Powercast."],["EXPLORE","Move through the library without losing context."],["RETURN","Come back to Naya without getting lost." ]],action:"player"}
];
const POS=[[50,9],[76,21],[91,50],[78,79],[50,91],[22,79],[9,50],[24,21],[50,25]];
const DESCRIPTIONS={1:"Imagine an AI that remembers what matters.",2:"Meet the idea of a compounding Super Brain.",3:"The case for ending AI amnesia.",4:"Why your AI should be a 10.",5:"Drive your AI with intention, not random prompts.",6:"Turn AI into a personal sparring partner.",7:"Build an intelligence partner that grows with you.",8:"The AI operational partner changes how work moves.",9:"A closer look at the Naya Power Superbrain.",10:"Working software is not the same thing as an extraordinary system.",11:"What happens when top AIs grade Naya Power?",12:"A founder's letter about ending AI amnesia.",13:"The Human–AI Intelligence Opera.",14:"The Naya Power Operating Model.",15:"A blueprint for collective wisdom.",16:"Welcome to NayaNET. Escape AI exhaustion.",17:"Curing human forgetfulness with Naya AI.",18:"What makes a compounding Super Brain?"};
const state={name:"",view:"door",world:null,casts:[],track:0,playing:false};
const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;

function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2400)}
function setAria(view){["frontDoor","hub","worldView","playerView"].forEach(id=>{const el=$("#"+id);const active=id===view;el.classList.toggle("active",active);el.setAttribute("aria-hidden",String(!active))})}
function setView(view,mode="push",world=state.world){state.view=view;setAria(view);if(mode==="push"){history.pushState({view,world,track:state.track},"",location.pathname+"#"+view+(world?"/"+world:""))}}
function enter(){const input=$("#nameInput"),name=input.value.trim();if(!name){input.focus();input.parentElement?.classList.add("invalid");toast("Enter your name to enter NayaNET.");return}input.parentElement?.classList.remove("invalid");state.name=name;localStorage.setItem("nayanetName",name);$("#welcomeName").textContent="WELCOME, "+name.toUpperCase();setView("hub");$("#nayaState").textContent="READY FOR YOU";toast("You're in. Naya is at the center.")}
function exit(){state.name="";localStorage.removeItem("nayanetName");$("#nameInput").value="";state.world=null;state.view="door";setAria("frontDoor");history.replaceState({view:"door"},"",location.pathname)}
function home(mode="push"){state.world=null;setView("hub",mode)}
function renderWorlds(){const root=$("#worlds");root.innerHTML=WORLDS.map((w,i)=>{const [x,y]=POS[i];return `<button class="world" data-world="${w.id}" aria-label="Open ${w.name}" style="left:${x}%;top:${y}%;--glow:${w.glow}"><span class="world-icon">${w.icon}</span><span class="world-name">${w.name}</span></button>`}).join("");$$('.world').forEach(el=>{el.addEventListener("pointerenter",()=>nayaAware(el.dataset.world));el.addEventListener("focus",()=>nayaAware(el.dataset.world));el.addEventListener("click",()=>openWorld(el.dataset.world))})}
function nayaAware(id){const w=WORLDS.find(x=>x.id===id);if(!w)return;$("#nayaState").textContent=w.name.toUpperCase();$("#nayaCore").dataset.aware="true"}
function resetNaya(){setTimeout(()=>{if(state.view==="hub")$("#nayaState").textContent=state.name?"READY FOR YOU":"YOUR INTELLIGENCE PARTNER"},1200)}
function openWorld(id){const world=WORLDS.find(w=>w.id===id);if(!world)return;state.world=id;if(world.action==="player"){openPlayer(true);return}renderWorld(world);setView("worldView");$("#worldContent").focus({preventScroll:true});$("#nayaState").textContent=world.name.toUpperCase()}
function renderWorld(w){$("#worldCrumb").textContent="NAYANET · "+w.name.toUpperCase();const action=w.action==="score"?"OPEN MAXESS":w.action==="challenge"?"START 5-DAY":"ASK NAYA";$("#worldAction").textContent=action;$("#worldContent").innerHTML=`<div class="world-hero" style="--glow:${w.glow}"><div class="world-copy"><div class="kicker">${w.kicker}</div><h2>${w.title}</h2><p>${w.copy}</p><div class="world-actions"><button class="world-primary" data-primary>${w.action==="score"?"DISCOVER AI SCORE →":w.action==="challenge"?"START THE FIVE-DAY →":"ASK NAYA →"}</button><button class="world-secondary" data-back>RETURN TO NAYA</button></div></div><div class="hero-object" style="--glow:${w.glow}"><span>${w.icon}</span></div></div><div class="world-pillars">${w.items.map((item,i)=>`<article class="pillar"><b>0${i+1} · ${item[0]}</b><p>${item[1]}</p></article>`).join("")}</div>`;$("#worldContent").querySelector("[data-primary]").addEventListener("click",()=>worldPrimary(w));$("#worldContent").querySelector("[data-back]").addEventListener("click",()=>backToHub())}
function worldPrimary(w){if(w.action==="score"){window.location.href="https://aiscore.nayanet.app/";return}if(w.action==="player"){openPlayer(true);return}if(w.action==="challenge"){toast("Five-Day Challenge is ready for activation.");return}$("#nayaState").textContent="LISTENING";toast("Naya is listening. Tell her what you want to accomplish.")}
function backToHub(){state.world=null;home();$("#nayaState").textContent="RETURN";setTimeout(()=>$("#nayaState").textContent="READY FOR YOU",900)}
function routeBack(){if(state.view==="hub"||state.view==="door")return;history.back()}

function driveId(url){const match=url?.match(/\/d\/([^/]+)/);return match?match[1]:null}
function imageFor(c){const id=driveId(c.image);return id?`https://drive.google.com/thumbnail?id=${id}&sz=w1600`:""}
function audioFor(c){const id=driveId(c.audio);return id?`https://drive.google.com/uc?export=download&id=${id}`:c.audio}
async function loadCasts(){try{const response=await fetch("/powercasts.json",{cache:"no-store"});if(!response.ok)throw new Error("Powercast request failed");state.casts=await response.json()}catch(error){state.casts=[];toast("The Powercast library is preparing.")}if(state.casts.length){renderCasts();selectTrack(state.track,false)}}
function renderWave(){const root=$("#waveform");root.innerHTML=Array.from({length:30},(_,i)=>`<i style="--h:${25+((i*17)%70)}%"></i>`).join("")}
function renderCasts(){const root=$("#castGrid");root.innerHTML=state.casts.map((c,i)=>{const image=imageFor(c);return `<button class="cast ${i===state.track?"selected":""}" data-track="${i}" style="--c:${i%4===0?"#9b7cff":i%4===1?"#55e6ff":i%4===2?"#ffd56a":"#75f0ad"}" aria-label="Play ${c.title}"><span class="cast-art" ${image?`style="background-image:url('${image}')"`:""}></span><span class="cast-number">${String(c.n).padStart(2,"0")}</span><span class="cast-info"><small>POWERCAST ${String(c.n).padStart(2,"0")}</small><strong>${c.title}</strong></span></button>`}).join("");$$('.cast').forEach(el=>el.addEventListener("click",()=>selectTrack(Number(el.dataset.track),true)))}
function selectTrack(index,play){if(!state.casts.length)return;const i=(index+state.casts.length)%state.casts.length,c=state.casts[i],image=imageFor(c);state.track=i;$("#heroArt").style.backgroundImage=image?`linear-gradient(145deg,#08060d22,#020208bb),url('${image}')`:"linear-gradient(145deg,#121326,#04040a)";$("#heroNumber").textContent=String(c.n).padStart(2,"0");$("#heroTitle").textContent=c.title;$("#heroDescription").textContent=DESCRIPTIONS[c.n]||"Listen, think and carry the useful part forward.";$("#dockTitle").textContent=c.title;$("#dockNumber").textContent=String(c.n).padStart(2,"0");$("#dockArt").style.backgroundImage=image?`linear-gradient(#0002,#0008),url('${image}')`:"none";$("#audio").src=audioFor(c);$("#audio").load();$$('.cast').forEach((el,j)=>el.classList.toggle("selected",j===i));if(play)playAudio()}
function openPlayer(push=true){state.world="player";setView("playerView",push?"push":"replace");if(!$("#waveform").children.length)renderWave();if(!state.casts.length)loadCasts()}
function playAudio(){const audio=$("#audio");audio.play().then(()=>{state.playing=true;updatePlaybackUI();$("#nayaState").textContent="LISTENING"}).catch(()=>toast("Press play again to start the Powercast."))}
function pauseAudio(){const audio=$("#audio");audio.pause();state.playing=false;updatePlaybackUI();if(state.view==="hub")$("#nayaState").textContent="READY FOR YOU"}
function toggleAudio(){if($("#audio").paused)playAudio();else pauseAudio()}
function updatePlaybackUI(){const symbol=state.playing?"Ⅱ":"▶";$("#mainPlay .power-icon").textContent=symbol;$("#dockPlay").textContent=symbol;$("#playerView .player-console").classList.toggle("playing",state.playing);$("#audio").setAttribute("aria-label",state.playing?"Powercast playing":"Powercast paused")}
function formatTime(seconds){if(!Number.isFinite(seconds))return"0:00";return Math.floor(seconds/60)+":"+String(Math.floor(seconds%60)).padStart(2,"0")}

$("#entryForm").addEventListener("submit",e=>{e.preventDefault();enter()});$("#nameInput").addEventListener("input",()=>$("#nameInput").parentElement.classList.remove("invalid"));$("#hubBrand").addEventListener("click",()=>toast("You are home.") );$("#exitButton").addEventListener("click",exit);$("#nayaCore").addEventListener("click",()=>{state.view==="hub";$("#nayaState").textContent="LISTENING";toast("Naya is here. Choose a world, or tell her what you want to accomplish.")});$("#askNaya").addEventListener("click",()=>{ $("#nayaState").textContent="LISTENING";toast("Tell Naya what you want to create, learn or solve.")});$("#backButton").addEventListener("click",routeBack);$("#playerBack").addEventListener("click",routeBack);$("#playerClose").addEventListener("click",routeBack);$("#worldAction").addEventListener("click",()=>{const w=WORLDS.find(x=>x.id===state.world);if(w)worldPrimary(w)});$("#openPlayer").addEventListener("click",()=>openPlayer(true));$("#dockArt").addEventListener("click",()=>openPlayer(true));$("#dockPlay").addEventListener("click",toggleAudio);$("#mainPlay").addEventListener("click",toggleAudio);$("#prevTrack").addEventListener("click",()=>selectTrack(state.track-1,true));$("#nextTrack").addEventListener("click",()=>selectTrack(state.track+1,true));
$("#audio").addEventListener("timeupdate",()=>{const audio=$("#audio"),pct=audio.duration?(audio.currentTime/audio.duration)*100:0;$("#dockProgress").style.width=pct+"%";$("#currentTime").textContent=formatTime(audio.currentTime);$("#duration").textContent=formatTime(audio.duration)});$("#audio").addEventListener("play",()=>{state.playing=true;updatePlaybackUI()});$("#audio").addEventListener("pause",()=>{state.playing=false;updatePlaybackUI()});$("#audio").addEventListener("ended",()=>selectTrack(state.track+1,true));$("#audio").addEventListener("error",()=>toast("This Powercast source could not be played right now."));
window.addEventListener("keydown",event=>{if(event.key==="Escape"&&state.view!=="hub"&&state.view!=="door")routeBack()});window.addEventListener("popstate",event=>{const next=event.state?.view||"door",world=event.state?.world||null;state.world=world;if(next==="worldView"){const w=WORLDS.find(x=>x.id===world)||WORLDS[0];renderWorld(w);setView("worldView","replace",w.id)}else if(next==="playerView"){openPlayer(false)}else if(next==="hub"){setView("hub","replace");resetNaya()}else{setView("frontDoor","replace");state.world=null}});

const saved=localStorage.getItem("nayanetName");if(saved){state.name=saved;$("#nameInput").value=saved;$("#welcomeName").textContent="WELCOME, "+saved.toUpperCase()}
renderWave();renderWorlds();history.replaceState({view:"door",world:null,track:0},"",location.pathname);loadCasts();
