"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WORLDS=[
{id:"power",name:"Naya Power",icon:"☀",sub:"Your intelligence system",tone:"#9c7bff",title:"Think with more power.",copy:"Naya Power is the intelligence layer for thinking, learning, creating, remembering, organizing, communicating, discovering and accomplishing.",items:[["THINK","Turn questions into clearer thinking and better decisions."],["CREATE","Move from idea to useful work with an intelligent partner."],["GROW","Use every interaction to become more capable."]]},
{id:"brain",name:"Super Brain",icon:"✦",sub:"Private context",tone:"#9c7bff",title:"Build intelligence that stays with you.",copy:"Your private intelligence grows from meaningful experience, memory and context — so tomorrow can begin with what you learned today.",items:[["EXPERIENCE","What happens to you can become useful signal."],["MEMORY","Important context does not disappear with a chat."],["COMPOUND","Experience becomes reusable intelligence."]]},
{id:"identity",name:"Smart Identity",icon:"◈",sub:"Name · ID · Link",tone:"#f1cd78",title:"Be known by what you choose.",copy:"Your Smart Identity separates the person you are from the identity you choose to use on the network.",items:[["SMART NAME","Start with the name you choose."],["SMART ID","A deliberate network identity."],["SMART LINK","Connect without exposing everything."]]},
{id:"intelligence",name:"Intelligence",icon:"◇",sub:"Capture · learn · compound",tone:"#70e6a1",title:"Turn experience into intelligence.",copy:"Breakthroughs, lessons, decisions, questions and discoveries should not vanish into yesterday. Capture the useful part and carry it forward.",items:[["HUMAN NOTE","What you experienced."],["NAYA NOTE","What Naya understood."],["COMPOUND","What carries forward."]]},
{id:"maxess",name:"MAXESS",icon:"◉",sub:"AI capability",tone:"#9c7bff",title:"Discover what you're capable of.",copy:"MAXESS makes AI capability visible. See where you are, understand your strengths and discover the next move that can make you dramatically more capable.",items:[["ASSESS","A focused AI mastery assessment."],["UNDERSTAND","See capability clearly."],["ACT","Turn insight into a better way of working."]],action:"score"},
{id:"challenge",name:"5-Day Challenge",icon:"5",sub:"Activate momentum",tone:"#f1cd78",title:"Don't believe it. Try it.",copy:"Work with Naya on something real for five days. Create, learn, capture and compound — then look back and see what changed.",items:[["DAY 1","Meet the system and establish context."],["DAYS 2–4","Create, learn, capture and compound."],["DAY 5","Look back and see what changed."]],action:"challenge"},
{id:"spaces",name:"Intelligent Spaces",icon:"◎",sub:"Humans + AIs",tone:"#66e5ff",title:"Open a room around the work.",copy:"Bring people and intelligences together around one purpose. Private by default. Sharing happens by choice.",items:[["PEOPLE","Invite who belongs."],["AI","Bring Naya or other AIs into the work."],["PURPOSE","The space exists to help something happen."]]},
{id:"network",name:"Your Network",icon:"⊙",sub:"Connect intelligence",tone:"#66e5ff",title:"Let useful intelligence find useful intelligence.",copy:"NayaNET is not about exposing everyone to everyone. It is about meaningful connection, with consent at the boundary.",items:[["DISCOVER","Subjects, interests, questions and capabilities."],["CONNECT","Meet around ideas rather than identity alone."],["SHARE","Choose what wisdom can travel."]]},
{id:"player",name:"Power Player",icon:"▶",sub:"18 Powercasts",tone:"#f1cd78",title:"Listen. Think. Become more capable.",copy:"The Power Player is the heartbeat of NayaNET — a living listening experience built from the real Powercast library.",items:[["LISTEN","Choose a canonical Powercast."],["EXPLORE","Move through the library without losing context."],["RETURN","Come back to the Living Sun naturally." ]],action:"player"}
];
const POS=[[50,10],[76,19],[90,39],[82,67],[68,87],[32,87],[18,67],[10,39],[24,19]];
const DESC={1:"Imagine an AI that remembers what matters.",2:"Meet your compounding Superbrain.",3:"End AI amnesia and keep the useful context.",4:"Why your AI should be a 10.",5:"Drive your AI with intention, not random prompts.",6:"Turn AI into your personal sparring partner.",7:"Build a lifelong intelligence partner.",8:"The AI operational partner changes how work moves.",9:"A closer look at the Naya Power Superbrain.",10:"Working software is not the same thing as an extraordinary system.",11:"What happens when top AIs grade Naya Power?",12:"A founder's letter about ending AI amnesia.",13:"The Human–AI Intelligence Opera.",14:"The Naya Power Operating Model.",15:"A blueprint for collective wisdom.",16:"Welcome to NayaNET. Escape AI exhaustion.",17:"Curing human forgetfulness with Naya AI.",18:"What makes a compounding Super Brain?"};
const state={name:"",view:"frontDoor",world:null,casts:[],track:0,playing:false};
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2400)}
function show(id,push=true){state.view=id;["frontDoor","hub","worldView","playerView"].forEach(x=>{const e=$("#"+x),on=x===id;e.classList.toggle("active",on);e.setAttribute("aria-hidden",String(!on))});if(push)history.pushState({view:id,world:state.world},"",location.pathname+"#"+id+(state.world?"/"+state.world:""))}
function enter(){const input=$("#nameInput"),name=input.value.trim();if(!name){input.focus();toast("Your name opens NayaNET.");return}state.name=name;localStorage.setItem("nayanetName",name);$("#welcomeName").textContent="WELCOME, "+name.toUpperCase();show("hub");toast("You're in. Naya is ready.")}
function exit(){state.name="";state.world=null;state.playing=false;localStorage.removeItem("nayanetName");$("#nameInput").value="";show("frontDoor",false);history.replaceState({view:"frontDoor"},"",location.pathname)}
function renderWorlds(){const root=$("#worlds");root.innerHTML=WORLDS.map((w,i)=>{const [x,y]=POS[i];return `<button class="world" data-world="${w.id}" aria-label="Open ${w.name}" style="left:${x}%;top:${y}%;--tone:${w.tone}"><span class="world-icon">${w.icon}</span><span class="world-copy"><b class="world-name">${w.name}</b><small class="world-sub">${w.sub}</small></span></button>`}).join("");$$('.world').forEach(b=>{b.addEventListener("pointerenter",()=>focusWorld(b.dataset.world));b.addEventListener("focus",()=>focusWorld(b.dataset.world));b.onclick=()=>openWorld(b.dataset.world)})}
function focusWorld(id){const w=WORLDS.find(x=>x.id===id);if(w)$("#hubTitle").dataset.hover=w.name}
function openWorld(id){const w=WORLDS.find(x=>x.id===id);if(!w)return;state.world=id;if(w.action==="player"){openPlayer();return}renderWorld(w);show("worldView")}
function renderWorld(w){$("#worldTag").textContent="NAYANET · "+w.name.toUpperCase();$("#worldContent").innerHTML=`<div class="world-hero" style="--tone:${w.tone}"><div class="world-copy"><div class="kicker">${w.sub.toUpperCase()}</div><h1>${w.title}</h1><p>${w.copy}</p><div class="world-actions"><button class="world-primary" id="worldPrimary">${w.action==="score"?"DISCOVER YOUR AI SCORE →":w.action==="challenge"?"START THE FIVE-DAY →":"ASK NAYA →"}</button><button class="world-secondary" id="worldReturn">RETURN TO NAYA</button></div></div><div class="world-object"><span>${w.icon}</span></div></div><div class="world-grid">${w.items.map((x,i)=>`<article class="world-piece"><b>0${i+1} · ${x[0]}</b><p>${x[1]}</p></article>`).join("")}</div>`;$("#worldPrimary").onclick=()=>primary(w);$("#worldReturn").onclick=()=>show("hub")}
function primary(w){if(w.action==="score"){location.href="https://aiscore.nayanet.app/";return}if(w.action==="challenge"){toast("The Five-Day Challenge is ready for activation.");return}toast("Naya is listening. Tell her what you want to accomplish.")}
function driveId(u){const m=(u||"").match(/\/d\/([^/]+)/);return m?m[1]:null}function imageFor(c){const id=driveId(c.image);return id?`https://drive.google.com/thumbnail?id=${id}&sz=w1200`:""}function audioFor(c){const id=driveId(c.audio);return id?`https://drive.google.com/uc?export=download&id=${id}`:c.audio||""}
async function loadCasts(){try{const r=await fetch("/powercasts.json",{cache:"no-store"});if(!r.ok)throw Error();state.casts=await r.json()}catch(e){toast("Powercasts are still loading.");state.casts=[]}if(state.casts.length){renderCasts();selectTrack(state.track,false)}}
function renderCasts(){const root=$("#castGrid");root.innerHTML=state.casts.map((c,i)=>{const img=imageFor(c);return `<button class="cast ${i===state.track?"selected":""}" data-track="${i}" aria-label="Select Powercast ${c.n}: ${c.title}"><span class="cast-art" ${img?`style="background-image:url('${img}')"`:""}></span><span class="cast-number">${String(c.n).padStart(2,"0")}</span><span class="cast-info"><small>POWERCAST ${String(c.n).padStart(2,"0")}</small><strong>${c.title}</strong></span></button>`}).join("");$$('.cast').forEach(b=>b.onclick=()=>selectTrack(Number(b.dataset.track),true))}
function selectTrack(index,play){if(!state.casts.length)return;const i=(index+state.casts.length)%state.casts.length,c=state.casts[i],img=imageFor(c);state.track=i;state.playing=false;$("#heroCover").style.backgroundImage=img?`linear-gradient(145deg,#ffffff0a,#00000077),url('${img}')`:"none";$("#coverNumber").textContent=String(c.n).padStart(2,"0");$("#heroNumber").textContent=String(c.n).padStart(2,"0");$("#heroTitle").textContent=c.title;$("#heroDesc").textContent=DESC[c.n]||"Listen, think and carry the useful part forward.";$("#hubTitle").textContent=c.title;$("#hubDesc").textContent=DESC[c.n]||"Listen, think and carry the useful part forward.";$("#audio").src=audioFor(c);$("#audio").load();$$('.cast').forEach((e,j)=>e.classList.toggle("selected",j===i));play?playAudio():syncUI()}
function openPlayer(){state.world="player";show("playerView");if(!state.casts.length)loadCasts()}
function playAudio(){const a=$("#audio");if(!a.src){toast("Choose a Powercast first.");return}a.play().then(()=>{state.playing=true;syncUI();toast("Playing in NayaNET.")}).catch(()=>toast("Press play to start the Powercast."))}
function pauseAudio(){const a=$("#audio");a.pause();state.playing=false;syncUI()}
function toggle(){if($("#audio").paused)playAudio();else pauseAudio()}
function syncUI(){const icon=state.playing?"Ⅱ":"▶";$("#hubPlay").textContent=icon;$("#mainPlay").textContent=icon;$("#waveform").classList.toggle("playing",state.playing);$("#hubTitle").style.opacity=state.playing?"1":".94"}
function fmt(s){return Number.isFinite(s)?Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0"):"0:00"}
function renderWave(){const w=$("#waveform");w.innerHTML=Array.from({length:42},(_,i)=>`<i style="--h:${18+((i*23)%78)}%"></i>`).join("")}
$("#entryForm").onsubmit=e=>{e.preventDefault();enter()};$("#nameInput").oninput=()=>{};$("#exitButton").onclick=exit;$("#worldBack").onclick=()=>show("hub");$("#playerBack").onclick=()=>show("hub");$("#openPlayer").onclick=openPlayer;$("#artButton").onclick=openPlayer;$("#hubPlay").onclick=toggle;$("#mainPlay").onclick=toggle;$("#hubPrev").onclick=()=>selectTrack(state.track-1,state.playing);$("#hubNext").onclick=()=>selectTrack(state.track+1,state.playing);$("#prevTrack").onclick=()=>selectTrack(state.track-1,state.playing);$("#nextTrack").onclick=()=>selectTrack(state.track+1,state.playing);$("#askNaya").onclick=()=>toast("Naya is listening. Tell her what you want to create, learn or solve.");$$('[data-preview]').forEach(b=>b.onclick=()=>{if(b.dataset.preview==="player"){show("hub");openPlayer()}else{state.world=b.dataset.preview;const w=WORLDS.find(x=>x.id===state.world);if(w){renderWorld(w);show("worldView")}}});$$('[data-quick]').forEach(b=>b.onclick=()=>b.dataset.quick==="player"?openPlayer():openWorld(b.dataset.quick));$("#audio").ontimeupdate=()=>{const a=$("#audio"),p=a.duration?a.currentTime/a.duration*100:0;$("#hubProgress").style.width=p+"%";$("#currentTime").textContent=fmt(a.currentTime);$("#duration").textContent=fmt(a.duration);$("#hubCurrent").textContent=fmt(a.currentTime);$("#hubDuration").textContent=fmt(a.duration)};$("#audio").onplay=()=>{state.playing=true;syncUI()};$("#audio").onpause=()=>{state.playing=false;syncUI()};$("#audio").onended=()=>{selectTrack(state.track+1,true)};window.onpopstate=e=>{const v=e.state?.view||"hub";state.world=e.state?.world||null;show(v,false)};
renderWorlds();renderWave();const saved=localStorage.getItem("nayanetName");if(saved){state.name=saved;$("#nameInput").value=saved;$("#welcomeName").textContent="WELCOME, "+saved.toUpperCase()}
loadCasts();
