"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WORLDS=[
 {id:"power",name:"Naya Power",sub:"Your AI layer",icon:"☀",glow:"#9b6cff",kicker:"THE INTELLIGENCE LAYER",title:"Think with more power.",copy:"Naya Power turns AI from a conversation into an operating relationship — helping you think, learn, create, remember, organize, connect and accomplish.",pillars:[["THINK","Turn questions into clearer thinking and better decisions."],["REMEMBER","Keep the things that matter available when you need them."],["CREATE","Move from idea to finished work with an intelligent partner."]]},
 {id:"brain",name:"Super Brain",sub:"Your context",icon:"✦",glow:"#e85cff",kicker:"YOUR PRIVATE INTELLIGENCE",title:"Build intelligence that stays with you.",copy:"Your Super Brain is your private intelligent environment. Your experience, projects, lessons and context can become reusable intelligence without becoming public network data.",pillars:[["EXPERIENCE","What happens to you can become signal."],["MEMORY","Important context does not have to disappear with a chat."],["COMPOUND","Tomorrow starts with what you learned today."]]},
 {id:"identity",name:"Smart Identity",sub:"You control it",icon:"◈",glow:"#ffd56a",kicker:"YOUR IDENTITY",title:"Be known by what you choose.",copy:"NayaNET separates your private identity from your network identity. Your Smart ID can be the name you use to participate without exposing everything about you.",pillars:[["SMART NAME","Start with a human name you choose."],["SMART ID","Your network identity is distinct from private details."],["SMART LINK","Connect around a deliberate identity, not a data dump."]]},
 {id:"notes",name:"Smart Notes",sub:"Turn life into intelligence",icon:"◇",glow:"#75f0ad",kicker:"CAPTURE WHAT MATTERS",title:"Turn experience into intelligence.",copy:"A breakthrough, lesson, mistake, decision, goal or discovery should not vanish into yesterday. Capture the useful part and make tomorrow smarter.",pillars:[["HUMAN NOTE","What you experienced and said."],["NAYA NOTE","What Naya understood from it."],["BRIEFING","Review what happened, changed, mattered and comes next."]]},
 {id:"maxess",name:"MAXESS",sub:"Know your AI score",icon:"◉",glow:"#e85cff",kicker:"AI MASTERY",title:"Find your starting point.",copy:"MAXESS turns AI capability into something you can see, understand and improve. Take the assessment, discover your score and get a clear next move.",pillars:[["ASSESS","A focused AI mastery assessment."],["UNDERSTAND","See where your capability is strong and where it can grow."],["ACT","Turn the result into a better way of working with AI."]],action:"score"},
 {id:"challenge",name:"5-Day Challenge",sub:"Start compounding",icon:"5",glow:"#ffd56a",kicker:"FIVE DAYS",title:"Don't believe it. Try it.",copy:"Talk to Naya. Capture what matters. Work on something real. Learn from each day. Five days is enough to feel the difference between using AI and building intelligence with AI.",pillars:[["DAY 1","Meet the system and establish context."],["DAY 2–4","Create, learn, capture and compound."],["DAY 5","Look back and see what changed." ]],action:"challenge"},
 {id:"spaces",name:"Intelligent Spaces",sub:"Think together",icon:"◎",glow:"#55e6ff",kicker:"COLLABORATION",title:"Open a room around the work.",copy:"An Intelligent Space can bring a human, Naya, other AIs, or other people together around one purpose — privately by default, with sharing by choice.",pillars:[["PEOPLE","Invite the people who belong in the room."],["AI","Bring Naya or multiple AIs into the work."],["PURPOSE","The space exists to help something happen."]]},
 {id:"network",name:"Your Network",sub:"Find intelligence",icon:"⊙",glow:"#55e6ff",kicker:"INTELLIGENCE CAN FIND INTELLIGENCE",title:"Connect around what matters.",copy:"The future network is not about exposing everyone to everyone. It is about helping useful intelligence find useful intelligence — with consent at the boundary.",pillars:[["DISCOVER","Subjects, interests, questions, goals and capabilities."],["CONNECT","Meet people around ideas rather than identity alone."],["SHARE","Choose what wisdom can travel beyond your private space."]]},
 {id:"player",name:"Power Player",sub:"The heartbeat",icon:"▶",glow:"#ff78d6",kicker:"NAYA POWERCAST",title:"Listen. Think. Become more capable.",copy:"The Power Player is the heartbeat of NayaNET — real Powercasts, real ideas and a living listening experience that keeps the intelligence close at hand.",pillars:[["LISTEN","Select a Powercast and make it the experience."],["EXPLORE","Move through the canonical library without losing context."],["RETURN","Come back to Naya without getting lost."]],action:"player"}
];
const state={name:"",view:"door",world:null,casts:[],track:0};
const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2400)}
function setView(id,historyMode="push"){const ids=["frontDoor","hub","worldView","playerView"];ids.forEach(x=>$("#"+x).classList.toggle("active",x===id));state.view=id;if(historyMode==="push")history.pushState({view:id,world:state.world,track:state.track},"",location.pathname+"#"+id+(state.world?"/"+state.world:""))}
function enter(){const name=$("#nameInput").value.trim();if(!name){$("#nameInput").focus();toast("Enter your name to enter NayaNET.");return}state.name=name;localStorage.setItem("nayanetName",name);$("#welcomeName").textContent="WELCOME, "+name.toUpperCase();setView("hub");toast("You're in. Naya is at the center.")}
function home(){state.world=null;setView("hub");}
function exit(){state.name="";localStorage.removeItem("nayanetName");$("#nameInput").value="";history.replaceState({view:"door"},"",location.pathname);setView("frontDoor","replace");}
function openWorld(id){const w=WORLDS.find(x=>x.id===id);if(!w)return;state.world=id;if(id==="player"){openPlayer(true);return}renderWorld(w);setView("worldView")}
function renderWorld(w){$("#worldCrumb").textContent="NAYANET · "+w.name.toUpperCase();$("#worldAction").textContent=w.action==="score"?"OPEN MAXESS":w.action==="challenge"?"START 5-DAY":"ASK NAYA";$("#worldContent").innerHTML=`<div class="world-hero"><div class="world-copy"><div class="kicker">${w.kicker}</div><h2>${w.title}</h2><p>${w.copy}</p><div class="world-actions"><button class="world-primary" data-action="primary">${w.action==="score"?"DISCOVER AI SCORE →":w.action==="challenge"?"START THE FIVE-DAY →":"ASK NAYA →"}</button><button class="world-secondary" data-action="back">RETURN TO NAYA</button></div></div><div class="hero-object" style="--glow:${w.glow}44"><span>${w.icon}</span></div></div><div class="world-pillars">${w.pillars.map((p,i)=>`<article class="pillar"><b>0${i+1} · ${p[0]}</b><p>${p[1]}</p></article>`).join("")}</div>`;$("#worldContent").querySelector('[data-action="primary"]').onclick=()=>worldPrimary(w);$("#worldContent").querySelector('[data-action="back"]').onclick=home}
function worldPrimary(w){if(w.action==="score"){location.href="https://aiscore.nayanet.app/"}else if(w.action==="challenge"){toast("Five-Day Challenge: start with one real goal.")}else{toast("Naya is listening. Tell her what you want to accomplish.")}}
function idFromDrive(url){const m=url?.match(/\/d\/([^/]+)/);return m?m[1]:null}function imageFor(c){const id=idFromDrive(c.image);return id?`https://drive.google.com/thumbnail?id=${id}&sz=w1200`:""}function audioFor(c){const id=idFromDrive(c.audio);return id?`https://drive.google.com/uc?export=download&id=${id}`:c.audio}
async function loadCasts(){try{const r=await fetch("/powercasts.json",{cache:"no-store"});state.casts=await r.json()}catch(e){state.casts=[]}if(!state.casts.length){toast("Powercast library could not be loaded.");return}renderCasts();selectTrack(0,false)}
function renderCasts(){const grid=$("#castGrid");grid.innerHTML=state.casts.map((c,i)=>{const colors=["#9b6cff","#e85cff","#55e6ff","#ffd56a"];return `<button class="cast ${i===state.track?"selected":""}" data-track="${i}" style="--c:${colors[i%colors.length]}"><span class="cast-art"></span><span class="cast-number">${String(c.n).padStart(2,"0")}</span><span class="cast-info"><small>POWERCAST ${String(c.n).padStart(2,"0")}</small><strong>${c.title}</strong></span></button>`}).join("");$$('.cast').forEach(c=>c.onclick=()=>selectTrack(Number(c.dataset.track),true))}
function selectTrack(i,play){if(!state.casts[i])return;state.track=i;const c=state.casts[i],img=imageFor(c);$("#heroArt").style.backgroundImage=img?`linear-gradient(145deg,#08060d55,#08060dcc),url('${img}')`:"";$("#heroArt").style.backgroundSize="cover";$("#heroArt").style.backgroundPosition="center";$("#heroArt .art-number").textContent=String(c.n).padStart(2,"0");$("#heroTitle").textContent=c.title;$("#heroDescription").textContent=descriptionFor(c.n);$("#dockTitle").textContent=c.title;$("#dockArt").style.backgroundImage=img?`url('${img}')`:"";$("#dockArt").style.backgroundSize="cover";$("#dockArt span").textContent=String(c.n).padStart(2,"0");$("#audio").src=audioFor(c);$$('.cast').forEach((el,j)=>el.classList.toggle("selected",j===i));if(play)playAudio()}
function descriptionFor(n){const d={1:"Imagine an AI that remembers what matters.",2:"Meet the idea of a compounding Super Brain.",3:"The case for ending AI amnesia.",4:"Why your AI should be a 10.",5:"Drive your AI with intention, not random prompts.",6:"Turn AI into a personal sparring partner.",7:"Build an intelligence partner that grows with you.",8:"The AI operational partner changes how work moves.",9:"A closer look at the Naya Power Superbrain.",10:"Working software is not the same thing as an extraordinary system.",11:"What happens when top AIs grade Naya Power?",12:"A founder's letter about ending AI amnesia.",13:"The Human–AI Intelligence Opera.",14:"The Naya Power Operating Model.",15:"A blueprint for collective wisdom.",16:"Welcome to NayaNET. Escape AI exhaustion.",17:"Curing human forgetfulness with Naya AI.",18:"What makes a compounding Super Brain?"};return d[n]||"Listen, think and carry the useful part forward."}
function openPlayer(push=true){state.world="player";setView("playerView",push?"push":"replace");if(!state.casts.length)loadCasts()}
function playAudio(){const a=$("#audio");a.play().then(()=>{$("#mainPlay").textContent="Ⅱ";$("#dockPlay").textContent="Ⅱ";$("#playerView .player-console").classList.add("playing")}).catch(()=>toast("The Powercast is ready. Press play again to start audio."))}
function pauseAudio(){const a=$("#audio");a.pause();$("#mainPlay").textContent="▶";$("#dockPlay").textContent="▶";$("#playerView .player-console").classList.remove("playing")}
function toggleAudio(){const a=$("#audio");a.paused?playAudio():pauseAudio()}
function backFromWorld(){history.back()}
$("#entryForm").addEventListener("submit",e=>{e.preventDefault();enter()});$("#homeButton").onclick=home;$("#resetButton").onclick=exit;$("#nayaCore").onclick=()=>toast("Naya is here. Choose a world, or open the Power Player.");$("#askNaya").onclick=()=>toast("Tell Naya what you want to create, learn or solve.");$("#backButton").onclick=backFromWorld;$("#playerBack").onclick=backFromWorld;$("#playerClose").onclick=backFromWorld;$("#openPlayer").onclick=()=>openPlayer(true);$("#dockPlay").onclick=toggleAudio;$("#mainPlay").onclick=toggleAudio;$("#prevTrack").onclick=()=>selectTrack((state.track-1+state.casts.length)%state.casts.length,true);$("#nextTrack").onclick=()=>selectTrack((state.track+1)%state.casts.length,true);$("#audio").addEventListener("timeupdate",()=>{const a=$("#audio"),pct=a.duration?(a.currentTime/a.duration)*100:0;$("#dockProgress").style.width=pct+"%";$("#currentTime").textContent=formatTime(a.currentTime);$("#duration").textContent=formatTime(a.duration)});$("#audio").addEventListener("ended",()=>selectTrack((state.track+1)%state.casts.length,true));$("#audio").addEventListener("error",()=>toast("This source is hosted in Google Drive. Use the source link if the browser blocks playback."));function formatTime(n){if(!Number.isFinite(n))return"0:00";return Math.floor(n/60)+":"+String(Math.floor(n%60)).padStart(2,"0")}
window.addEventListener("popstate",e=>{const v=e.state?.view||"door";if(v==="hub")setView("hub","replace");else if(v==="worldView"){const w=WORLDS.find(x=>x.id===e.state?.world)||WORLDS[0];state.world=w.id;renderWorld(w);setView("worldView","replace")}else if(v==="playerView")openPlayer(false);else setView("frontDoor","replace")});
const saved=localStorage.getItem("nayanetName");if(saved){$("#nameInput").value=saved;state.name=saved}history.replaceState({view:"door"},"",location.pathname);loadCasts();
