from pathlib import Path
import re, shutil

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'20260817 912am RESULTS PAGE CODE'
BASELINE=ROOT/'BASELINE-NITRO-20260817.html'
MARK='<!-- MAXESS-NITRO-AAA-UPGRADE v1 -->'
END='<!-- /MAXESS-NITRO-AAA-UPGRADE -->'
NAYA='https://i.postimg.cc/dVXw7sRN/grok-image-f75a6f12-4e3a-4c99-a334-5684ba0f7401.jpg'

CSS=r'''<style id="maxess-nitro-aaa-css">
#maxess-results-10.v21-canonical{--n-purple:#9b63ff;--n-magenta:#ed5cff;--n-blue:#43a8ff;--n-teal:#38d7c0;--n-green:#54d98b;--n-yellow:#ffd35a;--n-orange:#ff934f;--n-red:#ff5757;overflow:hidden}
#maxess-results-10.v21-canonical .nitro-section{position:relative;isolation:isolate}
#maxess-results-10.v21-canonical .nitro-section:before{content:"";position:absolute;inset:0;z-index:-2;pointer-events:none;background:radial-gradient(circle at 8% 18%,rgba(155,99,255,.10),transparent 28%),radial-gradient(circle at 92% 72%,rgba(67,168,255,.08),transparent 26%)}
#maxess-results-10.v21-canonical .nitro-section:after{content:"";position:absolute;z-index:-1;right:-140px;top:28px;width:320px;height:210px;border-radius:52% 48% 61% 39%/45% 55% 45% 55%;background:radial-gradient(circle,rgba(237,92,255,.13),transparent 68%);filter:blur(10px);pointer-events:none}
#maxess-results-10.v21-canonical .nitro-naya{display:flex;align-items:center;gap:14px;width:min(760px,100%);margin:0 auto 28px;padding:12px 16px 12px 12px;border:1px solid rgba(155,99,255,.18);border-radius:999px;background:rgba(255,255,255,.74);box-shadow:0 14px 38px rgba(45,20,70,.10),inset 0 1px rgba(255,255,255,.95);backdrop-filter:blur(16px);color:#17131d}
#maxess-results-10.v21-canonical .nitro-naya img{width:48px;height:48px;flex:0 0 48px;border-radius:50%;object-fit:cover;border:2px solid #fff;box-shadow:0 5px 18px rgba(25,10,40,.22)}
#maxess-results-10.v21-canonical .nitro-naya-copy{min-width:0;text-align:left}.nitro-naya-copy b{display:block;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#7445ad}.nitro-naya-copy span{display:block;margin-top:3px;font-size:14px;line-height:1.35;color:#302a36}
#maxess-results-10.v21-canonical .nitro-naya button{margin-left:auto;min-height:42px;padding:0 14px;border:0;border-radius:999px;background:#120a18;color:#fff;font-weight:900;cursor:pointer}
#maxess-results-10.v21-canonical .nitro-radar-wrap{display:grid;grid-template-columns:minmax(260px,.95fr) minmax(0,1.05fr);gap:34px;align-items:center;max-width:1120px;margin:36px auto 0;padding:28px;border:1px solid rgba(255,255,255,.12);border-radius:38px;background:linear-gradient(145deg,rgba(255,255,255,.055),rgba(155,99,255,.06));box-shadow:0 28px 80px rgba(0,0,0,.24),inset 0 1px rgba(255,255,255,.10)}
#maxess-results-10.v21-canonical .nitro-radar{width:min(460px,100%);aspect-ratio:1;margin:auto;display:grid;place-items:center}.nitro-radar svg{width:100%;height:100%;overflow:visible}.nitro-radar-center{position:absolute;text-align:center;color:#fff;pointer-events:none}.nitro-radar-center b{display:block;font-size:56px;line-height:.8;letter-spacing:-.07em}.nitro-radar-center span{display:block;margin-top:12px;color:rgba(255,255,255,.58);font-size:9px;font-weight:900;letter-spacing:.18em;text-transform:uppercase}
#maxess-results-10.v21-canonical .nitro-score-read{display:grid;gap:10px}.nitro-score-read div{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:13px 14px;border-radius:18px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.09)}.nitro-score-read span{font-size:12px;color:rgba(255,255,255,.70)}.nitro-score-read b{font-size:20px}.nitro-score-read i{grid-column:1/-1;height:5px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden}.nitro-score-read i:after{content:"";display:block;width:var(--w);height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--c1),var(--c2))}
#maxess-results-10.v21-canonical .nitro-organic-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:28px}.nitro-organic{position:relative;min-height:210px;padding:28px;border:1px solid rgba(25,15,35,.10);border-radius:37% 63% 54% 46%/45% 39% 61% 55%;background:linear-gradient(145deg,#fff,#f2edf7);box-shadow:0 22px 55px rgba(25,10,45,.10);overflow:hidden}.nitro-organic:nth-child(2){border-radius:59% 41% 47% 53%/38% 56% 44% 62%;background:linear-gradient(145deg,#fff,#f4f8f7)}.nitro-organic:nth-child(3){border-radius:45% 55% 62% 38%/57% 43% 57% 43%;background:linear-gradient(145deg,#fff,#fff6ea)}.nitro-organic small{display:block;color:#7445ad;font-size:9px;font-weight:950;letter-spacing:.15em;text-transform:uppercase}.nitro-organic h3{margin-top:9px;font-size:clamp(24px,2.6vw,38px);line-height:.98}.nitro-organic p{margin:10px 0 0;color:#595260;font-size:14px;line-height:1.55}
#maxess-results-10.v21-canonical .nitro-lever{display:grid;grid-template-columns:auto 1fr;gap:18px;align-items:center;margin-top:28px;padding:22px;border-radius:28px;background:linear-gradient(135deg,#24103c,#6b32b6 55%,#9b63ff);color:#fff;box-shadow:0 28px 65px rgba(71,26,125,.28)}.nitro-lever-score{width:82px;height:82px;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.28);font-size:30px;font-weight:950}.nitro-lever b{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#e2c9ff}.nitro-lever strong{display:block;margin-top:5px;font-size:clamp(24px,3vw,42px);line-height:1}.nitro-lever p{margin:8px 0 0;color:rgba(255,255,255,.76);font-size:14px}
#maxess-results-10.v21-canonical .nitro-pathway{position:relative;overflow:hidden;border-radius:30px!important;background:linear-gradient(145deg,rgba(255,255,255,.07),rgba(255,255,255,.025))!important;border:1px solid rgba(255,255,255,.12)!important;box-shadow:0 20px 48px rgba(0,0,0,.20)!important}.nitro-pathway:before{content:"";position:absolute;right:-40px;top:-45px;width:130px;height:130px;border-radius:50%;background:radial-gradient(circle,rgba(155,99,255,.28),transparent 68%)}
#maxess-results-10.v21-canonical .nitro-final-naya{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:26px;border-radius:36px;background:radial-gradient(circle at 20% 0,rgba(237,92,255,.20),transparent 35%),linear-gradient(145deg,#160a23,#050307);border:1px solid rgba(208,168,255,.22);box-shadow:0 32px 85px rgba(0,0,0,.38)}.nitro-final-naya img{width:82px;height:82px;border-radius:50%;object-fit:cover;border:2px solid rgba(255,255,255,.35)}.nitro-final-naya h3{font-size:clamp(24px,3vw,40px);color:#fff}.nitro-final-naya p{margin:6px 0 0;color:rgba(255,255,255,.68);font-size:14px}.nitro-final-naya a{display:inline-flex;align-items:center;justify-content:center;min-height:54px;padding:0 20px;border-radius:999px;background:#fff;color:#111;text-decoration:none;font-weight:950}
@media(max-width:900px){#maxess-results-10.v21-canonical .nitro-radar-wrap{grid-template-columns:1fr}.nitro-organic-grid{grid-template-columns:1fr 1fr!important}}@media(max-width:650px){.nitro-naya{border-radius:28px!important;align-items:flex-start}.nitro-naya button{display:none}.nitro-organic-grid{grid-template-columns:1fr!important}.nitro-final-naya{grid-template-columns:auto 1fr!important}.nitro-final-naya a{grid-column:1/-1;width:100%}}@media(prefers-reduced-motion:reduce){.nitro-organic,.nitro-pathway{transition:none!important}}@media print{.nitro-naya button,.nitro-final-naya a{display:none!important}.nitro-radar-wrap,.nitro-organic,.nitro-final-naya{break-inside:avoid;page-break-inside:avoid}}
</style>'''

JS=r'''<script id="maxess-nitro-aaa-js">
(function(){'use strict';var root=document.getElementById('maxess-results-10');if(!root)return;var NAYA='__NAYA__';var done=false;
function clamp(n){return Math.max(0,Math.min(100,Number(n)||0));}function result(){return window.MAXESS_RESULT&&typeof window.MAXESS_RESULT==='object'?window.MAXESS_RESULT:null;}function dims(r){return (Array.isArray(r&&r.dimensions)?r.dimensions:[]).slice(0,5).map(function(x){return{name:String(x.name||''),score:clamp(x.score)}})}
function col(s){var z=[[0,[255,87,87]],[49,[255,147,79]],[64,[255,211,90]],[74,[84,217,139]],[84,[56,215,192]],[89,[67,168,255]],[94,[155,99,255]],[100,[237,92,255]]];s=clamp(s);for(var i=1;i<z.length;i++)if(s<=z[i][0]){var a=z[i-1],b=z[i],t=(s-a[0])/(b[0]-a[0]);return'rgb('+a[1].map(function(v,j){return Math.round(v+(b[1][j]-v)*t)}).join(',')+')'}return'rgb(237,92,255)'}
function line(sec,r){var t=(sec.textContent||'').toLowerCase(),d=dims(r),hi=d.slice().sort(function(a,b){return b.score-a.score})[0];if(t.indexOf('dimension')>=0)return'I can see the shape of your capability. Let’s look at how these five strengths work together.';if(t.indexOf('pattern')>=0)return'Your score is one number. Your pattern is the story underneath it.';if(t.indexOf('strength')>=0||t.indexOf('advantage')>=0)return'I want you to notice what is already working. Your strongest capability is '+(hi?hi.name:'one of your core dimensions')+'.';if(t.indexOf('lever')>=0||t.indexOf('opportunity')>=0)return'This is not a weakness. It is your most useful place to create leverage next.';if(t.indexOf('next')>=0||t.indexOf('action')>=0)return'Let’s turn insight into one clear move you can actually use.';if(t.indexOf('master')>=0||t.indexOf('pathway')>=0)return'These are capability doors. I’ll help you choose the ones that fit your result.';return'Hi. I’ve looked at your results. This isn’t your judgment. It’s your map.'}
function speak(s){try{if(window.speechSynthesis){speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(s);u.rate=.96;u.pitch=1.02;speechSynthesis.speak(u)}}catch(e){}}
function naya(sec,r){if(sec.querySelector('.nitro-naya'))return;var x=document.createElement('div');x.className='nitro-naya';x.innerHTML='<img src="'+NAYA+'" alt="Naya, your AI guide"><div class="nitro-naya-copy"><b>Naya · Your guide</b><span>'+line(sec,r)+'</span></div><button type="button">Listen</button>';x.querySelector('button').onclick=function(){speak(x.querySelector('span').textContent)};sec.insertBefore(x,sec.firstElementChild)}
function radar(r,hero){if(hero.querySelector('.nitro-radar-wrap'))return;var d=dims(r);if(d.length<5)return;var c=215,rad=145,p=[];for(var i=0;i<5;i++){var a=-Math.PI/2+i*Math.PI*2/5,rr=rad*d[i].score/100;p.push([c+Math.cos(a)*rr,c+Math.sin(a)*rr])}var rings='',axes='',labs='';for(var k=1;k<5;k++){var rr=rad*k/4,q=[];for(var j=0;j<5;j++){var a=-Math.PI/2+j*Math.PI*2/5;q.push((c+Math.cos(a)*rr)+','+(c+Math.sin(a)*rr))}rings+='<polygon points="'+q.join(' ')+'" fill="none" stroke="rgba(255,255,255,.12)"/>'}for(var j=0;j<5;j++){var a=-Math.PI/2+j*Math.PI*2/5;axes+='<line x1="215" y1="215" x2="'+(c+Math.cos(a)*rad)+'" y2="'+(c+Math.sin(a)*rad)+'" stroke="rgba(255,255,255,.10)"/>';labs+='<text x="'+(c+Math.cos(a)*(rad+30))+'" y="'+(c+Math.sin(a)*(rad+30))+'" text-anchor="middle" dominant-baseline="middle" fill="rgba(255,255,255,.7)" font-size="10" font-weight="800">'+d[j].name.replace(/&/g,'&amp;')+'</text>'}var svg='<svg viewBox="0 0 430 430" role="img" aria-label="Your five-dimension AI capability fingerprint"><defs><linearGradient id="nitroFill" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#38d7c0" stop-opacity=".58"/><stop offset="1" stop-color="#ed5cff" stop-opacity=".34"/></linearGradient></defs>'+rings+axes+'<polygon points="'+p.join(' ')+'" fill="url(#nitroFill)" stroke="#d8bdff" stroke-width="2"/>'+p.map(function(v,i){return'<circle cx="'+v[0]+'" cy="'+v[1]+'" r="5" fill="'+col(d[i].score)+'" stroke="#fff" stroke-width="2"/>'}).join('')+labs+'</svg>';var w=document.createElement('div');w.className='nitro-radar-wrap';w.innerHTML='<div class="nitro-radar"><div style="position:relative;width:100%;height:100%;display:grid;place-items:center">'+svg+'<div class="nitro-radar-center"><b>'+Math.round(clamp(r.overallScore))+'</b><span>AI mastery score</span></div></div></div><div class="nitro-score-read"></div>';var list=w.querySelector('.nitro-score-read');d.forEach(function(x){var row=document.createElement('div');row.innerHTML='<span>'+x.name+'</span><b>'+Math.round(x.score)+'</b><i style="--w:'+x.score+'%;--c1:'+col(Math.max(0,x.score-10))+';--c2:'+col(x.score)+'"></i>';list.appendChild(row)});hero.appendChild(w)}
function enhance(r){if(!root.classList.contains('v21-canonical'))return;var secs=[].slice.call(root.querySelectorAll('.v21-section'));if(!secs.length)return;secs.forEach(function(s){s.classList.add('nitro-section');naya(s,r)});radar(r,secs[0]);var s=clamp(r.overallScore),orb=root.querySelector('.v21-score-orb');if(orb){var c=col(s);orb.style.borderColor=c;orb.style.boxShadow='inset 0 0 90px color-mix(in srgb,'+c+' 28%,transparent),0 45px 110px rgba(0,0,0,.55),0 0 125px color-mix(in srgb,'+c+' 22%,transparent)'}var d=dims(r),low=d.slice().sort(function(a,b){return a.score-b.score})[0];if(low)secs.filter(function(x){var t=(x.textContent||'').toLowerCase();return t.indexOf('lever')>=0||t.indexOf('opportunity')>=0}).forEach(function(sec){if(sec.querySelector('.nitro-lever'))return;var b=document.createElement('div');b.className='nitro-lever';b.innerHTML='<div class="nitro-lever-score">'+Math.round(low.score)+'</div><div><b>Your highest-leverage opportunity</b><strong>'+low.name+'</strong><p>Not a weakness. A focused opportunity to create a disproportionate return.</p></div>';sec.appendChild(b)});[].forEach.call(root.querySelectorAll('.v21-master,.v21-action,.v21-cell'),function(x){x.classList.add('nitro-pathway')});var final=root.querySelector('.v21-cta-final');if(final&&!final.querySelector('.nitro-final-naya')){var f=document.createElement('div');f.className='nitro-final-naya';f.innerHTML='<img src="'+NAYA+'" alt="Naya"><div><h3>Let’s keep going.</h3><p>I know where you are. Now let’s turn your strongest capability into your next level.</p></div><a href="#">Listen to Naya</a>';f.querySelector('a').onclick=function(e){e.preventDefault();speak('I’ve looked at your results. Let’s turn your strongest capability into your next level.')};final.insertBefore(f,final.firstChild)}done=true;root.setAttribute('data-nitro-aaa','complete');root.setAttribute('data-nitro-score',String(Math.round(s)))}
function boot(){var n=0;(function tick(){n++;var r=result();if(r&&root.classList.contains('v21-canonical')){enhance(r);if(done)return}if(n<30)setTimeout(tick,100)})();if(window.MutationObserver)new MutationObserver(function(){var r=result();if(r&&!root.querySelector('.nitro-radar-wrap'))enhance(r)}).observe(root,{childList:true,subtree:true})}boot();
})();</script>'''
JS=JS.replace('__NAYA__',NAYA)

def main():
    if not SOURCE.exists(): raise SystemExit('MISSING AUTHORITATIVE ARTIFACT')
    text=SOURCE.read_text(encoding='utf-8')
    for token in ('window.MAXESS_RESULT','#maxess-results-10','v21-canonical','</html>'):
        if token not in text: raise SystemExit('SOURCE INTEGRITY FAILED: '+token)
    if MARK not in text:
        if not BASELINE.exists(): shutil.copy2(SOURCE,BASELINE)
        payload='\n'+MARK+'\n'+CSS+'\n'+JS+'\n'+END+'\n';i=text.lower().rfind('</body>')
        if i<0: raise SystemExit('NO BODY CLOSE')
        text=text[:i]+payload+text[i:]
    else:
        text=re.sub(re.escape(MARK)+r'.*?'+re.escape(END),MARK+'\n'+CSS+'\n'+JS+'\n'+END,text,flags=re.S,count=1)
    SOURCE.write_text(text,encoding='utf-8')
    print('NITRO AAA UPGRADE: COMPLETE')
    print('LINES:',len(text.splitlines()))
    print('BYTES:',len(text.encode()))
    print('DATA CONTRACT: window.MAXESS_RESULT')
    print('NAYA PROFILE: integrated')
    print('RADAR: integrated')
    print('NAYA CONVERSATIONAL PRESENCE: integrated')
    print('SCORE-RESPONSIVE ORB: integrated')
    print('ORGANIC VISUAL LANGUAGE: integrated')
    print('LEVER / NEXT-ACTION VISUAL: integrated')
    print('PRINT + REDUCED MOTION: integrated')
if __name__=='__main__':main()
